# ##################################################
#	Piece for smartphone orchestra
#			Tassos Tsesmetzis
# Description of the piece
# ##################################################

* Περιγραφή
** Γενικά
Το έργο "/Κομμάτι για ορχήστρα smartphone/" είναι για μη-καθορισμένο
αριθμό εκτελεστών οι οποίοι χρησιμοποιούν το smartphone ως μονάδα
παραγωγής ήχου. Έχει απροσδιόριστη διάρκεια και βασίζεται σε μια
λεκτική παρτιτούρα.

Ακουστικά είναι ένα δυνητικό παιχνίδι πάνω στα φαινόμενα του
διακροτήματος (beating) και της ωτοακουστικής εκπομπής (otoacoustic
emission) [1]. Σκοπός μου ήταν η παραγωγή ενός πλούσιου ηχοτοπίου με,
όσο γίνεται, ελάχιστα μέσα. Αυτή η επιλογή οφείλεται αφενός σε
αισθητικά κριτήρια, αφετέρου στους τεχνολογικούς και ακουστικούς
περιορισμούς που θέτουν οι συσκευές smartphone.

Ένα, ακόμη, στοιχείο που με ενδιαφέρει σ΄ αυτό το έργο, είναι η δημιουργία
/τοπικοτήτων ήχου/. Με τον όρο αυτό αναφέρομαι σε ακουστικά γεγονότα
που γίνονται αντιληπτά σε μια μικρή περιοχή μέσα στο χώρο της συναυλίας. Έτσι,
ο ακουστικός χώρος διαμερίζεται σε γεγονότα που γίνονται αντιληπτά από ολόκληρο
το ακροατήριο και γεγονότα που εκλαμβάνονται σε μικρότερες περιοχές γύρω
από τις συσκευές εκπομπής (διακροτήματα, ήχοι ωτοακουστικής εκπομπής, μεμονωμένες
συχνότητες).

Το έργο βασίζεται στις συχνότητες των ~1244.5079~, ~2489.0158~, ~4978.0317 Hz~
(ένα Eflat σε τρεις οκτάβες).
Ένας εκτελεστής μπορεί να επιλέξει κάθε στιγμή ένα ημιτονοειδή τόνο
σε μία από αυτές. Επιπλέον, μπορεί να μεταβάλλει τη συχνότητα κατά \pm 100 cents.
Η επιλογή των συχνοτήτων έγινε έτσι, ώστε, να ενισχύεται το ψυχοακουστικό
φαινόμενο των ήχων ωτοακουστικής εκπομπής. Η μεταβολή της συχνότητας μέχρι και
\pm 100 cents σε κάθε μεμονωμένο εκτελεστή, ενδέχεται να δημιουργήσει στο
συνολικό ήχο διακροτήματα, όσο και συνηχήσεις μικρότερες ή ίσες του τόνου
(modulo την οκτάβα).

Τεχνικά, το έργο χρησιμοποιεί τεχνολογίες διαδικτύου. Ιδιαίτερα, αξιοποιεί
το ~Web Audio API~ για τη σύνθεση του ήχου. Οι εκτελεστές συνδέονται στο δίκτυο και
κατευθύνονται στη σελίδα του κομματιού. Η διεπαφή της εφαρμογής αποτελείται από τρία
κουμπιά για την επιλογή της συχνότητας. Ο έλεγχος της έντασης και της απομάκρυνσης
από την κεντρική συχνότητα γίνεται με την κίνηση της συσκευής. Εδώ αξιοποιούνται οι αισθητήρες
επιταχυνσιόμετρο, γυροσκόπιο και μαγνητόμετρο.

Το "/Κομμάτι για ορχήστρα smartphone/" είναι ένα
παράδειγμα μιας συστημικής θεώρησης του έργου τέχνης. Αποτελεί συνέχεια των ερευνών μου κατά
την τελευταία δεκαετία.

** Περίπλοκα συστήματα
Ένα /περίπλοκο σύστημα/ είναι ένα σύστημα που αποτελείται από πολλά στοιχεία που αλληλεπιδρούν
μέσα σε ένα περιβάλλον [2]. Τα στοιχεία που αλληλεπιδρούν καλλούνται /agents/.
Στα /περίπλοκα συστήματα/, η συσσώρευση των μεμονωμένων αλληλεπιδράσεων ανάμεσα
στους /agents/, οδηγεί σε φαινόμενα που δεν υποδεικνύονται από τους κανόνες
αλληλεπίδρασης (emergence) [3, κεφ. 4]. Ένα ακόμη χαρακτηριστικό, που έχει τις ρίζες του
στην Κυβερνητική [4, κεφ. IV] και τη μη-γραμμική δυναμική [5], είναι η
ανατροφοδότηση (feedback).

Μια ιδιαίτερη κατηγορία /περίπλοκων συστημάτων/ είναι αυτά όπου οι /agents/ μπορούν να παραλλάσσουν
και να προσαρμόζουν τις συμπεριφορές τους βασιζόμενοι στην εμπειρία. Τα συστήματα αυτά αναφέρονται
ως /περίπλοκα προσαρμόσιμα συστήματα/ (/complex adaptive systems/) [9], [3].

** Το "/Κομμάτι για ορχήστρα smartphone/" ως /περίπλοκο προσαρμόσιμο σύστημα/
Στο "/Κομμάτι για ορχήστρα smartphone/", το ρόλο των agents παίζουν οι εκτελεστές που αλληλεπιδρούν
στο χώρο της συναυλίας. Οι τρόποι συμπεριφοράς τους καθορίζονται από μια λεκτική παρτιτούρα.
Κύρια αναφορά μου υπήρξαν οι λεκτικές παρτιτούρες της Pauline Oliveros [6]. Οι εκτελεστές
αντιδρούν στο συνολικό ήχο και προσαρμόζουν το παίξιμό τους ακολουθώντας τις οδηγίες της παρτιτούρας.

Λέξεις και σχέδια επιστρατεύονται στην παρτιτούρα για την ενεργοποίηση /νοητικών χώρων/ [7] σε κάθε
εκτελεστή. Αυτοί οι /νοητικοί χώροι/ τροποποιούνται κατά την εξέλιξη του κομματιού
και αλλάζουν μορφή με τις πρόβες και τις εκτελέσεις
του έργου. Αποτελούν μια αφηρημένη ιδέα για τη μορφή που πρέπει να έχει το κομμάτι
και παριστάνουν την /εσωτερική κατάσταση/ (/state/) [8, κεφ. 1] του /agent/.

/Βιβλιογραφία/

[1] Kendall GS, Haworth C, Cádiz RF. Sound Synthesis with Auditory Distortion Products. Computer Music Journal. 2014;38(4):5–23.

[2] "Complex Systems". Wikipedia, Wikimedia Foundation, accessed: 10/2020. https://en.wikipedia.org/wiki/Complex_system

[3] Miller JH, Page SE. Complex adaptive systems: an introduction to computational models of social life. Princeton, NJ: Princeton University Press; 2007.

[4] Wiener N. Cybernetics: or control and communication in the animal and the machine. Cambridge, MA: M.I.T. Press; 1989.

[5] Hale JK, Koçak Hüseyin. Dynamics and bifurcation. Berlin u.a.: Springer; 1991.

[6] Oliveros P, Pertl B. Anthology of text scores. New York: Deep Listening Publications; 2013.

[7] Fauconnier G, Turner M. Mental Spaces. In: Geeraerts D editor. Cognitive linguistics: basic readings. Berlin: Mouton de Gruyter; 2006.

[9] Holland JH. Hidden order: how adaptation builds complexity. Cambridge, MA: Perseus Books; 2003.
