# ##################################################
# Study for smartphone orchestra
# Piece A
# ##################################################

* Παρουσίαση
Το έργο "Κομμάτι για ορχήστρα smartphone" είναι για μη-καθορισμένο
αριθμό εκτελεστών οι οποίοι χρησιμοποιούν το smartphone ως μονάδα 
παραγωγής ήχου. Έχει απροσδιόριστη διάρκεια και βασίζεται σε μια
λεκτική παρτιτούρα.

Ακουστικά είναι ένα δυνητικό παιχνίδι πάνω στα φαινόμενα του
διακροτήματος (beating) και της ωτοακουστικής εκπομπής (otoacoustic 
emission). Σκοπός μου ήταν η παραγωγή ενός πλούσιου ηχοτοπίου με,
όσο γίνεται, ελάχιστα μέσα. Αυτή η επιλογή οφείλεται αφενός σε
αισθητικά κριτήρια (ένας ήχος στο στυλ έργων του Giacinto Scelsi), αφετέρου 
στους τεχνολογικούς και ακουστικούς περιορισμούς που θέτουν οι συσκευές
smartphone.

Το έργο βασίζεται πάνω στις συχνότητες ????, ένα Bb σε τρεις οκτάβες.
Ένας εκτελεστής μπορεί να επιλέξει κάθε στιγμή ένα ημιτονοειδή τόνο
σε μία από αυτές. Επιπλέον, μπορεί να μεταβάλει τη συχνότητα κατά \pm 100 cents. 
Η επιλογή των συχνοτήτων έγινε έτσι ώστε να ενισχύεται το ψυχοακουστικό 
φαινόμενο των ήχων ωτοακουστικής εκπομπής. Η μεταβολή της συχνότητας μέχρι και
\pm 100 cents σε κάθε μεμονωμένο εκτελεστή, ενδέχεται να δημιουργήσει στο 
συνολικό ήχο διακροτήματα, όσο και συνηχήσεις μικρότερες ή ίσες του τόνου 
(modulo την οκτάβα).

Τεχνικά το έργο χρησιμοποιεί τεχνολογίες διαδικτύου. Ιδιαίτερα, αξιοποιεί
το Web Audio API για τη σύνθεση του ήχου. Οι εκτελεστές συνδέονται σ' ένα τοπικό δίκτυο και
κατευθύνονται στη σελίδα του κομματιού. Το UI της εφαρμογής αποτελείται από τρία 
κουμπιά για την επιλογή της συχνότητας. Ο έλεγχος της έντασης και της απομάκρυνσης 
από την κεντρική συχνότητα γίνεται με την κίνηση της συσκευής. Εδώ αξιοποιούνται οι αισθητήρες.

Το "Κομμάτι για ορχήστρα smartphone" αποτελεί συνέχεια των ερευνών μου κατά
τη διάρκεια των μεταπτυχιακών σπουδών στο ΤΗΧΕΙ. Κυρίως, είναι ένα
παράδειγμα μιας συστημικής θεώρησης του έργου ΄τεχνης. Το έργο προκύπτει
ως το συνολικό αποτέλεσμα της αλληλεπίδρασης αυτόνομων μονάδων (agents) μέσα σε ένα περιβάλλον.
Στο "Κομμάτι για ορχήστρα smartphone", το ρόλο των agents παίζουν οι εκτελεστές που αλληλεπιδρούν
στο χώρο της συναυλίας.

Στα περίπλοκα συστήματα η συσσώρευση των μεμονωμένων αλληλεπιδράσεων ανάμεσα
στους agents, οδηγεί σε φαινόμενα που δεν υποδεικνύονται από τους κανόνες 
αλληλεπίδρασης (emergence). Ένα ακόμη χαρακτηριστικό, που έχει τις ρίζες του
στην Κυβερνητική (παραπ) και τη μη-γραμμική δυναμική (παραπ), είναι η 
ανατροφοδότηση (feedback). 

Στο έργο μου προσπάθησα να ενεργοποιήσω τα παραπάνω φαινόμενα με τη χρήση μιας
λεκτικής παρτιτούρας. Σ' αυτή αναγράφονται οι τρόποι συμπεριφοράς των agents.
Κυρίως είχα στο μυαλό μου (ως αναφορά) τις λεκτικές παρτιτούρες της Wendy Carlos
(παραπ). Επιπλέον, η παρτιτούρα περιλαμβάνει κάποια ελάχιστα σχέδια. Λέξεις και
σχέδια επιστρατεύονται για την ενεργοποίηση ενός νοητικού χώρου (παραπ) σε κάθε
εκτελεστή. Αυτός ο νοητικός χώρος τροποποιείται κατά την εξέλιξη του κομματιού
και αλλάζει μορφή με τις πρόβες και τις εκτελέσεις
του έργου. Αποτελεί μια αφηρημένη ιδέα για τη μορφή που πρέπει να έχει το κομμάτι
και παριστάνει την εσωτερική κατάσταση (state) του agent.
