# ##################################################
# Study for smartphone orchestra
# Piece A
# ##################################################

* Παρουσίαση
Το έργο "/Κομμάτι για ορχήστρα smartphone/" είναι για απροσδιόριστο
αριθμό εκτελεστών που χρησιμοποιούν το smartphone ως μονάδα 
παραγωγής ήχου. Έχει απροσδιόριστη διάρκεια και βασίζεται σε μια
λεκτική παρτιτούρα.

Ακουστικά είναι ένα δυνητικό παιχνίδι πάνω στα φαινόμενα του
διακροτήματος (beating) και της ωτοακουστικής εκπομπής (otoacoustic 
emission). Σκοπός μας ήταν η παραγωγή ενός πλούσιου ηχοτοπίου με,
όσο γίνεται, ελάχιστα μέσα. Αυτή η επιλογή οφείλεται αφενός σε
αισθητικά κριτήρια (ένας ήχος στο στυλ έργων του Giacinto Scelsi), αφετέρου 
στους τεχνολογικούς και ακουστικούς περιορισμούς που θέτουν οι συσκευές
smartphone.

Το έργο βασίζεται πάνω στις συχνότητες ????, ένα Bb σε τρεις οκτάβες.
Κάθε εκτελεστής μπορεί να επιλέγει κάθε στιγμή ένα ημιτονοειδή τόνο
σε μία από αυτές. Επιπλέον, μπορεί να μεταβάλει τη συχνότητα κατά \pm 100 cents. 
Η επιλογή των συχνοτήτων έγινε έτσι ώστε να ενισχύεται το ψυχοακουστικό 
φαινόμενο των ήχων ωτοακουστικής εκπομπής. Παραπέρα, μετακινώντας τη 
συχνότητα κατά \pm 100 cents (???), ενδέχεται να δημιουργηθούν διακροτήματα 
όσο και διαστήματα μέχρι τόνο.

Τεχνικά το έργο χρησιμοποιεί τεχνολογίες διαδικτύου και το Web Audio API (για 
τη σύνθεση του ήχου). Οι εκτελεστές συνδέονται σ' ένα τοπικό δίκτυο και
κατευθύνονται στη σελίδα του έργου. Το UI της εφαρμογής αποτελείται από τρία 
κουμπιά για την επιλογή της συχνότητας. Ο έλεγχοπς της έντασης και της απομάκρυνσης 
από την κεντρική συχνότητα γίνεται  χρησιμοποιώντας τους αισθητήρες της 
συσκευής.

Το "Κομμάτι για ορχήστρα smartphone" αποτελεί συνέχεια των ερευνών μας κατά
τη διάρκεια των μεταπτυχιακών σπουδών στο ??? ΤΗΧΕΙ. Κυρίως, είναι ένα 
παράγωγο μιας συστημικής θεώρησης του έργου ΄τεχνης. Το έργο είναι το 
αποτέλεσμα της αλληλεπίδρασης αυτόνομων μονάδων (agents) μέσα σε ένα περιβάλλον.
Στο έργο αυτό, το ρόλο των agents παίζουν οι εκτελεστές που αλληλεπιδρούν
στο χώρο της συναυλίας.

Στα περίπλοκα συστήματα οι συσσώρευση των μεμονωμένων αλληλεπιδράσεων ανάμεσα
στους agents, οδηγεί σε φαινόμενα που δεν υποδεικνύονται από τους κανόνες 
αλληλεπίδρασης (emergence). Ένα ακόμη χαρακτηριστικό, που έχει τις ρίζες του
στην Κυβερνητική (παραπ) και τη μη-γραμμική δυναμική (παραπ), είναι η 
ανατροφοδότηση (feedback). 

Στο έργο μου προσπάθησα να ενεργοποιήσω τα παραπάνω φαινόμενα με τη χρήση μιας
λεκτικής παρτιτούρας. Σ' αυτή προσδιορίζεται ο τρόπος συμπεριφοράς των agents.
Κυρίως είχα στο μυαλό μου (ως αναφορά) τις λεκτικές παρτιτούρες της Wendy Carlos
(παραπ). Επιπλέον, η παρτιτούρα περιλαμβάνει κάποια ελάχιστα σχέδια. Λέξεις και
σχέδια επιστρατεύονται για την ενεργοποίηση ενός νοητικού χώρου (παραπ) σε κάθε
εκτελεστή. Αυτός ο νοητικός χώρος αλλάζει μορφή με τις πρόβες και τις εκτελέσεις
του έργου. Αποτελεί μια αφηρημένη ιδέα για τη μορφή που πρέπει να έχει το κομμάτι.
