# ##################################################
# Study for smartphone orchestra
# Piece A
# ##################################################

* Παρουσίαση
Το έργο "/Κομμάτι για ορχήστρα smartphone/" είναι για μη-καθορισμένο
αριθμό εκτελεστών οι οποίοι χρησιμοποιούν το smartphone ως μονάδα 
παραγωγής ήχου. Έχει απροσδιόριστη διάρκεια και βασίζεται σε μια
λεκτική παρτιτούρα.

Ακουστικά είναι ένα δυνητικό παιχνίδι πάνω στα φαινόμενα του
διακροτήματος (beating) και της ωτοακουστικής εκπομπής (otoacoustic 
emission) [1]. Σκοπός μου ήταν η παραγωγή ενός πλούσιου ηχοτοπίου με,
όσο γίνεται, ελάχιστα μέσα. Αυτή η επιλογή οφείλεται αφενός σε
αισθητικά κριτήρια (ένας ήχος στο στυλ έργων του Giacinto Scelsi), αφετέρου 
στους τεχνολογικούς και ακουστικούς περιορισμούς που θέτουν οι συσκευές
smartphone.

Το έργο βασίζεται στις συχνότητες των 1244.5079, 2489.0158, 4978.0317 Hz
(ένα Eflat σε τρεις οκτάβες).
Ένας εκτελεστής μπορεί να επιλέξει κάθε στιγμή ένα ημιτονοειδή τόνο
σε μία από αυτές. Επιπλέον, μπορεί να μεταβάλει τη συχνότητα κατά \pm 100 cents. 
Η επιλογή των συχνοτήτων έγινε έτσι ώστε να ενισχύεται το ψυχοακουστικό 
φαινόμενο των ήχων ωτοακουστικής εκπομπής. Η μεταβολή της συχνότητας μέχρι και
\pm 100 cents σε κάθε μεμονωμένο εκτελεστή, ενδέχεται να δημιουργήσει στο 
συνολικό ήχο διακροτήματα, όσο και συνηχήσεις μικρότερες ή ίσες του τόνου 
(modulo την οκτάβα).

Τεχνικά το έργο χρησιμοποιεί τεχνολογίες διαδικτύου. Ιδιαίτερα, αξιοποιεί
το Web Audio API για τη σύνθεση του ήχου. Οι εκτελεστές συνδέονται σ' ένα τοπικό δίκτυο και
κατευθύνονται στη σελίδα του κομματιού. Το UI της εφαρμογής αποτελείται από τρία 
κουμπιά για την επιλογή της συχνότητας. Ο έλεγχος της έντασης και της απομάκρυνσης 
από την κεντρική συχνότητα γίνεται με την κίνηση της συσκευής. Εδώ αξιοποιούνται οι αισθητήρες 
επιταχυνσιόμετρο, γυροσκόπιο και μαγνητόμετρο.

Το "/Κομμάτι για ορχήστρα smartphone/" είναι ένα
παράδειγμα μιας συστημικής θεώρησης του έργου τέχνης. Αποτελεί συνέχεια των ερευνών μου κατά
την τελευταία δεκαετία. Το έργο συνιστά ένα σύστημα 
που διαμορφώνεται απο τις αλληλεπιδράσεις αυτόνομων μονάδων (agents) μέσα 
σε ένα περιβάλλον.
Στο "/Κομμάτι για ορχήστρα smartphone/", το ρόλο των agents παίζουν οι εκτελεστές που αλληλεπιδρούν
στο χώρο της συναυλίας.

Στα περίπλοκα συστήματα η συσσώρευση των μεμονωμένων αλληλεπιδράσεων ανάμεσα
στους agents, οδηγεί σε φαινόμενα που δεν υποδεικνύονται από τους κανόνες 
αλληλεπίδρασης (emergence) [2, κεφ. 4]. Ένα ακόμη χαρακτηριστικό, που έχει τις ρίζες του
στην Κυβερνητική [3, κεφ. IV] και τη μη-γραμμική δυναμική [4], είναι η 
ανατροφοδότηση (feedback). 
Στο έργο μου προσπάθησα να ενεργοποιήσω τα παραπάνω φαινόμενα με τη χρήση μιας
λεκτικής παρτιτούρας. Σ' αυτή αναγράφονται οι τρόποι συμπεριφοράς των agents.
Κύρια αναφορά μου υπήρξαν οι λεκτικές παρτιτούρες της Pauline Oliveros [5]. 
Επιπλέον, η παρτιτούρα περιλαμβάνει κάποια ελάχιστα σχέδια. Λέξεις και
σχέδια επιστρατεύονται για την ενεργοποίηση ενός νοητικού χώρου [6] σε κάθε
εκτελεστή. Αυτός ο νοητικός χώρος τροποποιείται κατά την εξέλιξη του κομματιού
και αλλάζει μορφή με τις πρόβες και τις εκτελέσεις
του έργου. Αποτελεί μια αφηρημένη ιδέα για τη μορφή που πρέπει να έχει το κομμάτι
και παριστάνει την εσωτερική κατάσταση (state) [7, κεφ. 1] του agent.

/Βιβλιογραφία/

[1] Kendall GS, Haworth C, Cádiz RF. Sound Synthesis with Auditory Distortion Products. Computer Music Journal. 2014;38(4):5–23.

[2] Miller JH, Page SE. Complex adaptive systems: an introduction to computational models of social life. Princeton, NJ: Princeton University Press; 2007.

[3] Wiener N. Cybernetics: or control and communication in the animal and the machine. Cambridge, MA: M.I.T. Press; 1989.

[4] Hale JK, Koçak Hüseyin. Dynamics and bifurcation. Berlin u.a.: Springer; 1991.

[5] Oliveros P, Pertl B. Anthology of text scores. New York: Deep Listening Publications; 2013.

[6] Fauconnier G, Turner M. Mental Spaces. In: Geeraerts D editor. Cognitive linguistics: basic readings. Berlin: Mouton de Gruyter; 2006.

[7] Holland JH. Hidden order: how adaptation builds complexity. Cambridge, MA: Perseus Books; 2003.
